apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-static-app     # 👈 This MUST match deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
